use enumset::EnumSet;

use crate::pre::*;

register_binaries!("tree-sitter", "vi", "vim", "nvim");
binary_dependencies!(
    Git, // various
    Clang, // compile tree sitter
    Diff, // undo tree
    Websocat, // yank to host
    Fzf, // various
    Rg, // various
    Python, // setup, various
    Node // installing lsp
);
config_dependencies!(Shellutils); // vinvim

version_cache!(static CFG = metadata::nvim::NVIM_CFG);

pub fn verify(_: &Context) -> cu::Result<Verified> {
    let v = check_cargo!("tree-sitter" in crate "tree-sitter-cli");
    check_outdated!(&v.version, metadata[nvim::treesitter_cli]::VERSION);
    check_in_shaft!("nvim");
    let stdout = command_output!("nvim", ["--version"]);
    let version_line = stdout.lines().next().unwrap_or("");
    let Some(version) = version_line.strip_prefix("NVIM v") else {
        cu::warn!("nvim --version returned unexpected output: {stdout}");
        return Ok(Verified::NotUpToDate);
    };
    check_outdated!(version, metadata[nvim]::VERSION);
    check_version_cache!(CFG);
    Ok(Verified::UpToDate)
}

pub fn download(_: &Context) -> cu::Result<()> {
    Ok(())
}

pub fn install(_: &Context) -> cu::Result<()> {
    Ok(())
}

pub fn configure(ctx: &Context) -> cu::Result<()> {
    hmgr::tools::ensure_unpacked()?;
    let config = ctx.load_config(CONFIG)?;
    let config_lua = config.to_lua();
    Ok(())
}

pub fn uninstall(_: &Context) -> cu::Result<()> {
    Ok(())
}

config_file! {
    static CONFIG: Config = {
        template: include_str!("config.toml"),
        migration: [],
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "kebab-case")]
struct Config {
    #[serde(default)]
    pub nvim_tree_git: bool,
    #[serde(default = "default_wsclip_host_port")]
    pub wsclip_host_port: u16,
}
fn default_wsclip_host_port() -> u16 {
    8881
}
impl Config {
    pub fn to_lua(&self) -> String {
        format!(r##"
-- Config generated by shaft
local M = {{
    nvim_tree_git = {nvim_tree_git},
    editorapi_ssh_wsclip_port = {wsclip_host_port},
}}
return M
        "##,
            nvim_tree_git = self.nvim_tree_git,
            wsclip_host_port = self.wsclip_host_port,
        )
    }
}
