version: '3'

tasks:
  copy:
    desc: >
      Copy config directory from this machine (~/.config/nvim)
      to shaft. Only works on Unix
    cmds:
      - rm -rf config
      - cp -R ~/.config/nvim config
      - rm -rf config/.git
      - rm -rf config/claudecode.nvim
      - rm -rf config/lua/piston/cache
      - rm -f config/.gitignore
      - rm -f config/lazy-lock.json
      - rm -f config/lua/piston/config_gen.lua
      - task: bump

  bump:
    - CURRENT=$(grep -oP 'NVIM_CFG = "\K[0-9]+' ../../registry/metadata.toml) && sed -i "s/NVIM_CFG = \"$CURRENT\"/NVIM_CFG = \"$((CURRENT+1))\"/" ../../registry/metadata.toml
    - rm -f ../../corelib/src/hmgr/tools.tar.gz
    - cargo build --manifest-path ../../corelib/Cargo.toml
    - cargo build --manifest-path ../../registry/Cargo.toml

